### ISSUE TITLE
Card features unable to save

### ISSUE THREAD

**Issue by kt-wawro** [pathfindertools/pl-launchpad#10]
While working on the Launchpad website. the photo cards feature will not save. This happens both when a picture is inserted and if you do not add a picture but just add text.
<img width="1728" alt="Screen Shot 2022-05-09 at 11 34 56 AM" src="https://user-images.githubusercontent.com/102541949/167446752-71d630cc-3336-446d-a627-afaed547f923.png">

Site: https://pl-launchpad.vercel.app/admin#/collections/pages

I also put in an issue on the microgen repo: kinked here: [
](https://github.com/pathfindertools/microgen/issues/46)

**Comment by tbenbow** [comment]
Fixed!
